apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netcat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netcat
    app.kubernetes.io/part-of: trillian
  name: netcat
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: netcat
status:
  loadBalancer: {}
